language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y apache2 libapache2-mod-fastcgi

before_script:
  - tools/travis_setup.sh

script: bin/phpspec r && bin/behat